const fs=require('node:fs');const assert=require('node:assert/strict');
const worker=fs.readFileSync('src/worker.js','utf8');
const migration=fs.readFileSync('migrations/0001_community_foundation.sql','utf8');
const community=fs.readFileSync('public/community.html','utf8');
const about=fs.readFileSync('public/aboutus.html','utf8');
const communityCss=fs.readFileSync('public/about-community.css','utf8');
const privacy=fs.readFileSync('public/privacy.html','utf8');
const config=fs.readFileSync('wrangler.jsonc','utf8');
const authRoutes=fs.readFileSync('src/routes/auth.js','utf8');
const communityJs=fs.readFileSync('public/community.js','utf8');

for(const table of ['users','sessions','email_tokens','files','comments','comment_files','reports','appeals','moderation_actions','outbox','audit_logs','consent_records','export_jobs'])assert.match(migration,new RegExp(`CREATE TABLE ${table}\\b`),`missing ${table} table`);
assert.match(migration,/author_user_id TEXT REFERENCES users\(id\) ON DELETE SET NULL/,'comments must survive account deletion without retaining the account link');
assert.match(worker,/COMMUNITY_ENABLED !== 'true'/,'community APIs must fail closed until production configuration is complete');
assert.match(worker,/Cf-Access-Jwt-Assertion|adminRoutes/,'admin API must be protected by Cloudflare Access JWT validation');
assert.match(config,/cananalysis-preview/,'preview resources must be isolated');
assert.match(config,/dead_letter_queue/,'mail delivery must have a dead letter queue');
assert.match(about,/crossBorderConsent/,'registration must request separate cross-border consent');
assert.match(about,/评论需要登录并验证邮箱后发布/,'comments must require a verified account');
for(const control of ['commentPrompt','commentExpansion','authCard','loginForm','registerForm','profileForm','passwordForm','exportButton','deleteAccountButton','resendForm','forgotForm','commentForm','comments'])assert.match(about,new RegExp(`id="${control}"`),`missing embedded community control ${control}`);
assert.ok(about.indexOf('id="comments"')<about.indexOf('id="commentPrompt"'),'existing comments must appear before the comment entry row');
assert.match(about,/id="commentPrompt"[^>]+aria-expanded="false"[^>]+aria-disabled="true" disabled><span>发表评论<\/span><small id="sessionSummary">暂未开放<\/small>/,'comment entry must be visibly unavailable and disabled');
assert.match(about,/id="commentExpansion" class="comment-expansion hidden"/,'login and registration controls must stay collapsed until requested');
assert.doesNotMatch(about,/<dialog|id="authDialog"|id="openAuthButton"/,'authentication must expand inline instead of opening a separate modal');
assert.match(communityCss,/\.community-board\{[^}]*background:transparent[^}]*box-shadow:none/s,'community board must use the page background instead of a separate dark panel');
assert.match(communityCss,/\.comment-prompt\{[^}]*background:transparent!important/s,'comment entry must keep the page background');
assert.match(communityJs,/const commentsOpen = !commentPrompt\.disabled/,'disabled comment entry must also be guarded in JavaScript');
assert.match(communityCss,/html\[data-skin="light"\] \.auth-tabs button\.active[^}]*color:#111827/s,'active login and registration tabs must keep dark text in the light theme');
assert.doesNotMatch(about,/href="\/community"/,'About page must not link to a separate community page');
assert.match(community,/location\.replace\('\/aboutus'/,'legacy community URL must redirect to the embedded area');
assert.match(authRoutes,/\/aboutus\?verify=.*#community/,'verification mail must return to the embedded community area');
assert.match(authRoutes,/\/aboutus\?reset=.*#community/,'password reset mail must return to the embedded community area');
assert.match(privacy,/Cloudflare Workers、D1、R2、Queues、Turnstile 和 Access/,'privacy policy must disclose Cloudflare processing');
for(const page of ['public/privacy.html','public/terms.html','public/community-guidelines.html','public/admin.html'])assert.equal(fs.existsSync(page),true,`${page} must exist`);
console.log('PASS: community schema, account gating, admin protection, environment isolation and legal disclosures');
